### ISSUE TITLE
Orb not displaying status of overall workflow, only the most recent job

### ISSUE THREAD

**Issue by scwheele** [CircleCI-Public/jira-connect-orb#17]
### Orb version

1.0.5

### What happened

The state of the most recent job will be the workflow status reported in Jira.

"For instance, if RSpec takes the longest to run and fails then I’ll see failed in Jira but if cucumber takes the longest and passes while rubocop fails, I’ll see passed in Jira."

### Expected behavior

See a single status in JIRA that shows the build status, linking to the entire workflow.

**Comment by nbialostosky** [comment]
This is still occurring with version `1.3.0`, and affects workflows that have a job that has parallelization. If you split a job into 10 containers, and one of those containers fails, the workflow itself is failed.

However, if the failing job is not the last job to complete out of the parallel runs, the status still shows as passing in Jira (since the last job to run passed). 

This is occurring since each parallel run will execute the Orb command and send it's status. Right now we hardcode that the job is "passing" if the workflow is still running when checking the workflow 'status':

https://github.com/CircleCI-Public/jira-connect-orb/blob/977fd6b04b6a5552b053655972c878f4e4de1bc1/src/commands/notify.yml#L114-L119

At least for fixing the parallel run issue we may need to check for if the job has parallelism via this endpoint: https://circleci.com/docs/api/v2/#tag/Job

Then as each parallel run completes it checks the status of the other parallel runs in the same above endpoint and sets the status based on that, meaning if any of the parallel runs are failing it sends a failing status.

**Comment by KyleTryon** [comment]
This issue as alluded to by @nbialostosky is difficult to resolve with orb-based notifications as they happen within the context of a job. We are trying to move to a webhook-based model which will have workflow-based notifications.

The new iteration of the jira integration will come at the end of the next quarter and should address these issues. We will close this issue for now and respond with an update once the new integration is released.
