### ISSUE TITLE
CIRCLE_TOKEN only accepts user token

### ISSUE THREAD

**Issue by thauanz** [CircleCI-Public/jira-connect-orb#56]
### Orb version

1.3.0

### What happened

Hi there, I wonder why my CIRCLE_TOKEN value has to be my personal token if the project is company-wide? If the idea is to check me, it will be **me** every time. :confused: 

### Expected behaviour

Use an ORG token instead of the personal.

**Comment by gmemstr** [comment]
This isn't strictly related to the Jira orb, and is more of a general CircleCI feature request. Will surface internally to find out where to direct this feedback - thanks!

**Comment by felicianotech** [comment]
Likely on [CircleCI Ideas](https://ideas.circleci.com/).

**Comment by gmemstr** [comment]
Closing this, since it doesn't relate to this project - as @felicianotech pointed out, you can file an idea on our feature request board. Alternatively, and something we suggest to customers, using a bot or machine user with a dedicated API key is a good solution (we use that route ourselves in many places!).
