### ISSUE TITLE
Supported Workflows

### ISSUE THREAD

**Issue by byule** [CircleCI-Public/jira-connect-orb#8]
Hi There -

Can you provide additional information in the README regarding the ideal workflows for this ORB to properly notify Jira of issue state?  From looking at the code, it appears as though it will only notify of an issue if it can read the issue number in the most recent commit.  

Imagine a gitflow workflow (https://datasift.github.io/gitflow/IntroducingGitFlow.html) where a 'release' to master is a single deploy that contains many commits in a develop branch.  Would this be usable in that case?

**Comment by iynere** [comment]
please see the usage examples for examples @byule 

https://circleci.com/orbs/registry/orb/circleci/jira#usage-examples

**Comment by eddiewebb** [comment]
@byule  - it should still read all since the orb uses the same API that shows commit summary in our UI for PRs.
i.e. --
<img width="667" alt="Screen Shot 2019-05-09 at 8 17 15 PM" src="https://user-images.githubusercontent.com/5262154/57500246-952ea100-7297-11e9-8047-4fc4b932421b.png">

The other approach is that now in versions 1.0.3 and above you can set the issue as part of the branch name , i.e. `features/PROJ-123`

**Comment by byule** [comment]
Yup - I made an assumption this would only scan the last commit after a
merge but it does in fact scan all the commits.  Works really well with our
existing workflows.

Thanks!
